name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Archive Production Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: dist
      #     path: dist
      #     if-no-files-found: error
      #     retention-days: 1

      # Refactor this to work on firebase
      # - uses: [username]/action-aws-cli@v1.1
      # - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
      # env:
      #   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
          # args: firebase target:apply hosting container tv2022-mfe-dashboard
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
